version: "3.7"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:sonarr
    volumes:
      - /datato/sonarr/data:/config
      - /shows:/tv #optional
      - /downloads:/downloads #optional

    ports:
      - 8989:8989
    restart: unless-stopped