version: "3.7"
services:
  code-server:
    image: code:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD= #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD= #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=your.domain.com #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /datato/code/config:/config
    ports:
      - 5000:5000
      - 8443:8443
    restart: unless-stopped
