version: "3.7"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:readarr
    volumes:
      - /datato/readarr/data:/config
      - /books:/books #optional
      - /downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped