version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    restart: unless-stopped
    ports:
      - 13378:80
    volumes:
      - /audiobooks:/audiobooks
      - /podcasts:/podcasts
      - /datato/audiobookshelf/config:/config
      - /datato/audiobookshelf/metadata:/metadata