version: "3.7"
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
        - LOG_LEVEL=debug
        - TZ=Europe/Berlin
    ports:
        - 5055:5055
    volumes:
        - /datato/jellyseer/config:/app/config
    restart: unless-stopped