version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    #ports:
    #  - "8385:80"
    environment:
      - PUID=
      - PGID=
    volumes:
      - /:/srv
      - ./filebrowser.db:/database/filebrowser.db
      - ./filebrowser/settings.json:/config/settings.json
    networks:
      - default
networks:
  default:
    external: true
    name: net
