version: "3.7"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:radarr
    volumes:
      - /datato/radarr/data:/config
      - /films:/films #optional
      - /downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped