services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
      - PUID=
      - PGID=
      #- DOCKER_HUB_USERNAME=USER #optional
      #- DOCKER_HUB_PASSWORD=PASS #optional
      #- DOCKER_MTU=1500 #optional
    volumes:
      - ./kasm:/opt
      #- /path/to/profiles:/profiles #optional
      #- /dev/input:/dev/input #optional
      #- /run/udev/data:/run/udev/data #optional
    #ports:
      #- 3113:3000
      #- 1443:443
    restart: unless-stopped

networks:
  default:
    external: true
    name: net
