version: '3.3'
services:
  redis:
      image: redis:alpine
      restart: always
      command: redis-server --save "" --appendonly "no"
      tmpfs:
        - /var/lib/redis
      cap_drop:
        - ALL
      cap_add:
        - SETGID
        - SETUID
        - DAC_OVERRIDE
  searxng:
      image: elestio/searxng:latest
      restart: always
      ports:
        - 8080:8080
      volumes:
        - /datato/searx:/etc/searxng:rw
      environment:
        - SEARXNG_BASE_URL=https://your.domain.com
      cap_drop:
        - ALL
      cap_add:
        - CHOWN
        - SETGID
        - SETUID
        - DAC_OVERRIDE
      logging:
          driver: "json-file"
          options:
              max-size: "1m"
              max-file: "1"