version: "3.7"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:jackett
    volumes:
      - /datato/jackett:/config
      - /datato/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped