version: "3"

services:
  vikunja:
    image: elestio/vikunja:${SOFTWARE_VERSION_TAG}
    restart: always
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://${DOMAIN}
      VIKUNJA_DATABASE_HOST: vikunja-db
      VIKUNJA_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: ${POSTGRES_USER}
      VIKUNJA_DATABASE_DATABASE: ${POSTGRES_DB}
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SERVICE_JWTSECRET}
    #ports:
    #  - 7070:3456
    volumes:
      - ./files:/app/vikunja/files
    depends_on:
      - vikunja-db


  vikunja-db:
    image: elestio/postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    #ports:
    #  - 37241:5432
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  default:
    external: true
    name: net

volumes:
  vikunja_data:
  postgres_data:
