version: "3.7"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /datato/freshrss:/config
    ports:
      - 80:80
    restart: unless-stopped