services:
  db:
    container_name: photoview-db
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - /datato/photoview/db_data:/var/lib/mysql
  photoview:
    container_name: photoview-server
    image: viktorstrate/photoview:2
    restart: unless-stopped
    ports:
      - 8083:80
    depends_on:
      - db
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - MAPBOX_TOKEN=your-token-here
    volumes:
      - /datato/photoview/api_cache:/app/cache
      - /photos:/photos:ro
volumes:
  db_data: null
  api_cache: null
